/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: u9iv4MUuC4PzWABABWMHXD
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsxDQpfQyIcEp } from "../mucho_3_d/PlasmicGlobalVariant__Screen"; // plasmic-import: xDQpfQY_icEP/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsxDQpfQyIcEp
});
